// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkilsgajuratxosaccmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdraWxzZ2FqdXJhdHhvc2FjY21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyODE5MjgsImV4cCI6MjA1MDg1NzkyOH0.CE5z9jJkXPi6gDBUwEX01_KacldNypQFaSl0s5QBvDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);